updated comments for clarity

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-shopt -s dotglob
-set -e
+shopt -s dotglob    # enables commands like 'mv *' to see hidden files
+set -e              # exit immediately if any command fails (non-zero status)
 
 # buildpack debug output
 pwd
@@ -19,7 +19,7 @@ echo $cache_dir
 echo $buildpack_dir
 env
 
-# download and compile nginx
+# download and build nginx
 mkdir -p $cache_dir
 cd $cache_dir
 wget http://nginx.org/download/nginx-1.6.2.tar.gz
@@ -28,25 +28,25 @@ cd nginx-1.6.2
 ./configure
 make
 
-# copy only needed files
-cd $cache_dir
-mkdir -p $cache_dir/nginx/logs
+# create hierarchy with only needed files
 mkdir -p $cache_dir/nginx/bin
 mkdir -p $cache_dir/nginx/conf
+mkdir -p $cache_dir/nginx/logs
 cp $cache_dir/nginx-1.6.2/objs/nginx $cache_dir/nginx/bin/nginx
 cp $cache_dir/nginx-1.6.2/conf/nginx.conf $cache_dir/nginx/conf/nginx.conf
 cp $cache_dir/nginx-1.6.2/conf/mime.types $cache_dir/nginx/conf/mime.types
 
 # move applicaiton files into public directory
 mkdir -p $cache_dir/public
-cp $cache_dir/nginx-1.6.2/html/50x.html $cache_dir/public/50x.html
 mv $app_files_dir/* $cache_dir/public/
+# copy nginx error template
+cp $cache_dir/nginx-1.6.2/html/50x.html $cache_dir/public/50x.html
 
-# move final files into place
+# put everything in place for droplet creation
 mv $buildpack_dir/bin/launch.sh $app_files_dir/
 mv $cache_dir/public $app_files_dir/
 mv $cache_dir/nginx $app_files_dir/
 
-# remove manifest
+# ensure manifest not in public directory
 if [ -f $cache_dir/public/manifest.yml ]; then rm $cache_dir/public/manifest.yml; fi
 if [ -f $cache_dir/public/stackato.yml ]; then rm $cache_dir/public/stackato.yml; fi
